title: SkyFormOps
description: Cloud & IT Networking Consulting for Small Businesses and Corporations
baseurl: "" # leave empty if using root
url: "https://ascension2anotherdimension.github.io/SKYFORMOPS" # replace with your GitHub username

# Activate the remote theme plugin
plugins:
  - jekyll-remote-theme

# Choose your theme (modern minimalist example)
remote_theme: benbalter/retlab

# Optional navigation
navigation:
  - name: Home
    link: /
  - name: Services
    link: /services
  - name: Contact
    link: /contact
